#!/usr/bin/env python3
"""
generate-theme-overrides.py

根据用户指定的品牌色、圆角偏好等参数，生成 L1 令牌覆盖文件 (overrides.css)。
在 tokens.css 之后引入即可实现风格定制。

用法:
  python3 generate-theme-overrides.py \
    --primary "#7c3aed" \
    --radius-scale 1.5 \
    --output overrides.css

参数:
  --primary        品牌主色 (hex，如 #7c3aed)
  --danger         危险色 (hex，默认 #ff4d4f)
  --success        成功色 (hex，默认 #22c55e)
  --warning        警告色 (hex，默认 #f59e0b)
  --radius-scale   圆角缩放倍数 (float，1.0=默认，2.0=双倍圆润)
  --bg-base        主背景色 (hex，默认 #ffffff)
  --text           主文字色 (hex，默认 #2b2b2b)
  --font-family    自定义字体栈 (string)
  --output         输出文件路径 (默认 overrides.css)
  --theme-key      data-theme 选择器值 (默认 mc)
"""

import argparse
import re
import sys
import colorsys


def hex_to_rgb(hex_color):
    """Convert hex color to RGB tuple (0-255)."""
    hex_color = hex_color.lstrip("#")
    if len(hex_color) == 3:
        hex_color = "".join(c * 2 for c in hex_color)
    return tuple(int(hex_color[i:i+2], 16) for i in (0, 2, 4))


def rgb_to_hex(r, g, b):
    """Convert RGB tuple to hex string."""
    return "#{:02x}{:02x}{:02x}".format(int(r), int(g), int(b))


def adjust_lightness(hex_color, factor):
    """Adjust lightness of a color. factor > 1 = lighter, < 1 = darker."""
    r, g, b = hex_to_rgb(hex_color)
    h, l, s = colorsys.rgb_to_hls(r/255, g/255, b/255)
    l = max(0, min(1, l * factor))
    r2, g2, b2 = colorsys.hls_to_rgb(h, l, s)
    return rgb_to_hex(r2*255, g2*255, b2*255)


def generate_primary_palette(primary_hex):
    """From a single primary color, derive the full 5-token palette."""
    r, g, b = hex_to_rgb(primary_hex)
    return {
        "primary": primary_hex,
        "primary-hover": adjust_lightness(primary_hex, 0.82),
        "primary-strong": adjust_lightness(primary_hex, 0.65),
        "primary-bg": adjust_lightness(primary_hex, 1.85),
        "primary-ring": "rgba({}, {}, {}, .15)".format(r, g, b),
    }


def generate_danger_palette(danger_hex):
    """Derive danger palette."""
    return {
        "danger": danger_hex,
        "danger-strong": adjust_lightness(danger_hex, 0.85),
        "danger-bg": adjust_lightness(danger_hex, 1.85),
    }


def scale_radius(base_values, scale):
    """Scale all radius values by a factor."""
    result = {}
    for key, val in base_values.items():
        if val == "9999px":
            result[key] = val  # full 不缩放
        elif key.startswith("radius-bubble"):
            # 非对称圆角：逐个缩放
            parts = val.split()
            scaled = " ".join(
                "{:.0f}px".format(float(p.replace("px", "")) * scale) for p in parts
            )
            result[key] = scaled
        elif val.endswith("px"):
            num = float(val.replace("px", ""))
            result[key] = "{:.0f}px".format(num * scale)
        else:
            result[key] = val
    return result


DEFAULT_RADII = {
    "radius-xs": "2px",
    "radius-sm": "4px",
    "radius-md": "6px",
    "radius-lg": "8px",
    "radius-xl": "10px",
    "radius-2xl": "14px",
    "radius-pill-sm": "18px",
    "radius-pill": "20px",
    "radius-full": "9999px",
    "radius-bubble-them": "4px 10px 10px 10px",
    "radius-bubble-me": "10px 4px 10px 10px",
}


def build_css(theme_key, overrides):
    """Build the final CSS override file content."""
    lines = [
        '@charset "UTF-8";',
        "/* ============================================================= */",
        "/* Theme overrides - auto-generated by generate-theme-overrides.py */",
        "/* Import after tokens.css to apply customizations               */",
        "/* ============================================================= */",
        "",
        '[data-theme="{}"] {{'.format(theme_key),
    ]

    if overrides:
        for key, val in overrides.items():
            lines.append("  --mc-{}: {};".format(key, val))

    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Generate theme override CSS for TRTC Room UIKit"
    )
    parser.add_argument("--primary", help="Brand primary color (hex)")
    parser.add_argument("--danger", help="Danger color (hex)")
    parser.add_argument("--success", help="Success color (hex)")
    parser.add_argument("--warning", help="Warning color (hex)")
    parser.add_argument(
        "--radius-scale",
        type=float,
        default=1.0,
        help="Radius scale factor (1.0=default, 2.0=rounder)",
    )
    parser.add_argument("--bg-base", help="Main background color (hex)")
    parser.add_argument("--text", help="Main text color (hex)")
    parser.add_argument("--font-family", help="Custom font family stack")
    parser.add_argument("--output", default="overrides.css", help="Output file path")
    parser.add_argument(
        "--theme-key", default="mc", help='data-theme selector value'
    )

    args = parser.parse_args()

    overrides = {}

    # Primary palette
    if args.primary:
        if not re.match(r"^#[0-9a-fA-F]{3,6}$", args.primary):
            print("Error: --primary must be a valid hex color (e.g., #7c3aed)")
            sys.exit(1)
        palette = generate_primary_palette(args.primary)
        for k, v in palette.items():
            overrides["color-" + k] = v

    # Danger palette
    if args.danger:
        palette = generate_danger_palette(args.danger)
        for k, v in palette.items():
            overrides["color-" + k] = v

    # Success
    if args.success:
        overrides["color-success"] = args.success

    # Warning
    if args.warning:
        overrides["color-warning"] = args.warning

    # Background
    if args.bg_base:
        overrides["color-bg-base"] = args.bg_base

    # Text
    if args.text:
        overrides["color-text"] = args.text

    # Font family
    if args.font_family:
        overrides["font-family"] = args.font_family

    # Radius scale
    if args.radius_scale != 1.0:
        scaled = scale_radius(DEFAULT_RADII, args.radius_scale)
        for k, v in scaled.items():
            overrides[k] = v

    if not overrides:
        print("Warning: No overrides specified. Run with --help for options.")
        print("Generating empty override file anyway.")

    css = build_css(args.theme_key, overrides)

    with open(args.output, "w", encoding="utf-8") as f:
        f.write(css)

    print("Generated: {} ({} overrides)".format(args.output, len(overrides)))


if __name__ == "__main__":
    main()
